"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ApiClientError, subscriptionApi, type Subscription } from "@/lib/api-client";

type Sort = "renewal" | "name" | "amount";
function decimal(value: Subscription["amount"]) { return typeof value === "number" ? value : Number(value.$numberDecimal); }
function displayAmount(subscription: Subscription) { return new Intl.NumberFormat(undefined, { style: "currency", currency: subscription.currency }).format(decimal(subscription.amount)); }
function displayDate(date: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(date)); }

export function SubscriptionList() {
  const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [cycle, setCycle] = useState("all"); const [sort, setSort] = useState<Sort>("renewal");
  useEffect(() => { void subscriptionApi.list().then(({ subscriptions }) => setSubscriptions(subscriptions)).catch((cause: unknown) => setError(cause instanceof ApiClientError ? cause.message : "We could not load your subscriptions.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => subscriptions.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()) && (status === "all" || item.status === status) && (cycle === "all" || item.billingCycle === cycle)).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "amount" ? decimal(a.amount) - decimal(b.amount) : new Date(a.renewalDate).getTime() - new Date(b.renewalDate).getTime()), [subscriptions, search, status, cycle, sort]);
  if (loading) return <p className="py-12 text-center text-slate-600" role="status">Loading subscriptions…</p>;
  if (error) return <p className="rounded-md bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>;
  return <section><div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium">Search<input className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search subscriptions" /></label><Select label="Status" value={status} onChange={setStatus} options={["all", "active", "paused", "cancelled"]} /><Select label="Billing cycle" value={cycle} onChange={setCycle} options={["all", "weekly", "monthly", "quarterly", "yearly"]} /><Select label="Sort by" value={sort} onChange={(value) => setSort(value as Sort)} options={["renewal", "name", "amount"]} /></div>{filtered.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><h2 className="text-lg font-semibold">{subscriptions.length === 0 ? "No subscriptions yet" : "No matching subscriptions"}</h2><p className="mt-2 text-slate-600">{subscriptions.length === 0 ? "Add your first subscription to start tracking renewals." : "Try adjusting your search or filters."}</p>{subscriptions.length === 0 && <Link className="mt-5 inline-block rounded-md bg-blue-700 px-4 py-2 text-sm font-medium text-white" href="/subscriptions/new">Add a subscription</Link>}</div> : <div className="grid gap-4 md:grid-cols-2">{filtered.map((item) => <article key={item._id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-sm text-slate-600">{item.category || "Uncategorised"} · {item.billingCycle}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium capitalize text-slate-700">{item.status}</span></div><p className="mt-5 text-2xl font-bold">{displayAmount(item)}</p><p className="mt-2 text-sm text-slate-600">{item.isTrial ? "Trial ends" : "Renews"} {displayDate(item.isTrial && item.trialEndDate ? item.trialEndDate : item.renewalDate)}</p></article>)}</div>}</section>;
}
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="text-sm font-medium">{label}<select className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 capitalize" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option} value={option}>{option === "all" ? "All" : option === "renewal" ? "Next renewal" : option}</option>)}</select></label>; }
