"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Protected } from "@/components/auth-provider";
import { ApiClientError, subscriptionApi, type Subscription } from "@/lib/api-client";

export default function SubscriptionPage() { return <Protected><Details /></Protected>; }
function Details() { const { id } = useParams<{ id: string }>(); const router = useRouter(); const [item, setItem] = useState<Subscription | null>(null); const [error, setError] = useState(""); const [pending, setPending] = useState(false); useEffect(() => { void subscriptionApi.get(id).then(({ subscription }) => setItem(subscription)).catch((cause: unknown) => setError(cause instanceof ApiClientError ? cause.message : "We could not load this subscription.")); }, [id]); async function change(status: "active" | "paused" | "cancelled") { setPending(true); try { setItem((await subscriptionApi.setStatus(id, status)).subscription); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "Unable to update subscription."); } finally { setPending(false); } } async function remove() { if (!confirm("Delete this subscription permanently?")) return; setPending(true); try { await subscriptionApi.remove(id); router.replace("/subscriptions"); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "Unable to delete subscription."); setPending(false); } } if (error && !item) return <main className="mx-auto max-w-2xl p-8"><p role="alert">{error}</p></main>; if (!item) return <main className="grid min-h-screen place-items-center" role="status">Loading subscription…</main>; return <main className="mx-auto min-h-screen max-w-2xl px-6 py-12"><Link className="text-sm font-medium text-blue-700" href="/subscriptions">← All subscriptions</Link><div className="mt-5 rounded-2xl border bg-white p-6"><p className="text-sm capitalize text-slate-600">{item.status} · {item.billingCycle}</p><h1 className="mt-2 text-3xl font-bold">{item.name}</h1><p className="mt-4 text-lg">Renews {new Date(item.renewalDate).toLocaleDateString()}</p>{error && <p className="mt-4 text-sm text-red-700" role="alert">{error}</p>}<div className="mt-7 flex flex-wrap gap-3"><Link className="rounded-md border px-4 py-2 font-medium" href={`/subscriptions/${id}/edit`}>Edit</Link>{item.status === "active" && <button className="rounded-md border px-4 py-2" disabled={pending} onClick={() => change("paused")}>Pause</button>}{item.status !== "cancelled" && <button className="rounded-md border px-4 py-2" disabled={pending} onClick={() => change("cancelled")}>Cancel</button>}{item.status !== "active" && <button className="rounded-md border px-4 py-2" disabled={pending} onClick={() => change("active")}>Reactivate</button>}<button className="rounded-md bg-red-700 px-4 py-2 text-white" disabled={pending} onClick={remove}>Delete</button></div></div></main>; }
